index:
    path: /
    controller: App\Controller\DefaultController::index

aula1:
    path: /aula1
    controller: App\Controller\DefaultController::aula1

block:
    path: /block
    controller: App\Controller\DefaultController::blockExtends
